### ISSUE TITLE
Migrate to IPython 3

### ISSUE THREAD

**Issue by minad** [SciRuby/iruby#1]
1. The next iruby gem version starting from iruby 0.2 will drop support for IPython versions < 3
2. The iruby 0.1 series will still continue IPython 2, but only urgent bug fixes will be backported

This change is necessary since IPython3 introduces protocol changes and is optimized for other language kernels. With IPython4, the language agnostic part will go to the project http://jupyter.org/

See original issues:
* https://github.com/minad/iruby/issues/39 (Discussion about versions)
* https://github.com/minad/iruby/issues/1, https://github.com/minad/iruby/issues/33  (Issue with iruby directory, we will follow the IPython3 convention for other language kernels starting from version 0.2)
* https://github.com/minad/iruby/issues/5 (CSS issue, revisit this for IPython 3)

**Comment by sebroeder** [comment]
Would it be possible to break this issue down a little more so that people new to the topic can help out? Is iRuby 0.1.x currently compatible with iPython 3 or not?

From my personal tests (as somebody new to the topic)  `iruby console` seems to work and `iruby notebook` starts the server successfully but only offers the python kernel, not the ruby kernel.

What would be the next step to expose the iruby kernel to the notebook frontend? My guess would be implementing [IPEP 25: Registry of installed kernels](https://github.com/ipython/ipython/wiki/IPEP-25:-Registry-of-installed-kernels)? Has work on this already started? Is there any documentation covering the migration for existing kernels to iPython 3? Maybe we can learn something from the Haskell project at https://github.com/gibiansky/IHaskell/commits/jupyter?

I tried to wrap my head around this but would really love to have some more information from somebody familiar with the code base.

**Comment by minad** [comment]
At first we have to find out what changed with IPython 3, what changed in the protocol and how can we register our kernel. There are changelogs in ipython and the IPEPs but afaik there is no migration guide.

As you already suggested the registry would be a good place to start.  In fact you already started by going through some docs :)

**Comment by sebroeder** [comment]
OK, here is what I found out so far (tested on OS X 10.10.2)…

1. Create the directory structure for the new kernelspec:

```bash
mkdir ~/.ipython/kernels/ruby
```

2. Put the following contents in a file `~/.ipython/kernels/ruby/kernel.json`:

```json
{
  "argv": [ "iruby", "kernel", "{connection_file}" ],
  "display_name": "Ruby",
  "language": "ruby"
}
```

3. Run `ipython console --kernel ruby` or `ipython notebook`. Both should work without crashing and the Ruby kernel should be available in the notebook GUI.

This should be all to make the old iruby kernel compatible with ipython3.
Note though that this uses the older protocol version 4, not the new version 5, so this is just a first step:

```
Kernel 86791499-3e4e-40e5-8af5-e7f66d9e81e6 speaks protocol 4.0 
```

**Comment by minad** [comment]
Very good. Currently iruby acts as a wrapper around ipython. So we have to change it in such a way that iruby creates this kernel.json file and executes ipython.

iruby console --> ipython console --kernel ruby
iruby notebook --> ipython notebook

The next step is then to update the protocol. Do you want to work on a patch?

**Comment by sebroeder** [comment]
I was thinking about getting rid of the wrapper completely for IPython 3+/Jupyter, and let the user invoke ` ipython console --kernel ruby` or `ipython notebook` directly. This IMHO better reflects the general direction of the Jupyter project and other non-Python kernel projects.

But to make this happen we would need to find a way to put `kernel.json` & friends in the users home dir when installing the iruby gem and I could not find a good way to archive this with rubygems. There is a `post_install` hook in rubygems that sounded promising but this is meant to be used for rubygems plugins, so not what I was locking for.

Any ideas and opinions, both about ditching the wrapper and a possible way to set up the kernel.json at install time?

I would like to work on this some more next week (after my math exam). If we get basic support for IPython 3 in, I would prefer improving the documentation and writing a test suite first, before we update to the protocol v5. A more comprehensive documentation should make it easier for new users to install iruby and a test suite makes it easier for us to change the code without breaking things to badly.

**Comment by minad** [comment]
# Wrapper

Yes, I thought about that before, also about this post_install idea. I agree that it would be in the spirit of jupyter to have no wrapper. However I think it would work better if we provide a simple one. It is shorter to type and also doesn't cost much. You don't have to use it, it is just there to get started quickly. If you want to use ipython/jupyter directly you will still be able to do that.

Installing via post_install hook is much messier and also makes it harder for package maintainers, like Debian etc. I don't want gems to write files in a post_install hook. This is very bad style. So I would definitely try to avoid the post_install/any install time solution, I would even prefer if the user has to write this kernel.json by hand.

My preferrable solution would be:

1. Create a very reduced wrapper which does nothing except for creating the kernel.json if it doesn't exist already
2. Pass all other commands through to ipython --kernel ruby
3. Provide a kernel subcommand which launches the kernel. I wouldn't do it the way you proposed above with eval, seems like a hack and exposes to much of IRuby to the kernel.json.

What I am proposing is similar to what we already have and the situation will still be much better than now, where we do too much intrusive messing around in the ipython config directory.

What do you think?

# Protocol update/Test suite/Documentation

What you propose is fine with me. I think we won't do another release before the protocol update, documentation and tests are done. Maybe the order doesn't matter.

Do you plan to apply for the GSOC?

**Comment by sebroeder** [comment]
OK, not that the math exam is done, I can think about more interesting stuff like this again :)

I though about the wrapper vs. no wrapper discussion some more and pretty much agree to your points. If we would have to come up with insane install hacks to archive the setup tasks that are currently done by the wrapper, than it is not worth it. I also agree on not using eval in the kernel.json.

I'll make myself familiar with the code in `lib/iruby/command.rb` and try to improve the wrapper to work with ipython 3.

I would like to add a subcommand like `--add-kernelspec/--remove-kernelspec` or `--register-kernel/--unregister-kernel` to the wrapper that can be used explicitly (by a user who otherwise does not want to use the wrapper) for one-time setup, so that the iruby kernel works with `ipython --kernel ruby` und `ipython notebook` without requiring the user to write the `kernel.json` by hand. Do you think this would be a sensible approach? This should also help solving minad/iruby#33.

I had a look at the GSOC page and I am interested in handing in an application. Could we follow up on that topic via email?

Thanks for your detailed feedback so far.

**Comment by minad** [comment]
`iruby register` and `iruby unregister` are a good idea. Still I would provide a notebook command etc just to get started quickly. I think there are people who just want to use it and don't want to know how IPython handles kernels etc.

So in total we have the following subcommands:

* register (Creates kernel.json)
* unregister (Deletes kernel.json)
* kernel (Starts the kernel, only used internally and in the kernel.json)
* console/qtconsole etc are passed to IPython with `--kernel ruby` appended
* the rest of the commands are just passed through to ipython as is

This is not much work and will work for everybody's purpose :)

About GSOC - just drop me an email and also write to the sciruby mailing list.

**Comment by sebroeder** [comment]
> Still I would provide a notebook command etc just to get started quickly. I think there are people who just want to use it and don't want to know how IPython handles kernels etc.

Yes, I didn't intent to remove the other subcommands, just add `register/unregister`. The subcommand list you provided looks good to me.

**Comment by liudangyi** [comment]
1. Since IRuby uses a different profile other than IPython, users may still need to use `iruby notebook` rather than `ipython notebook --kernel ruby`.
2. Same reason as 1., it seems unnecessary to provide a register / unregister method.

So should we use the same profile as IPython or not?

**Comment by liudangyi** [comment]
Also, SciRuby/iruby needs a new branch 'ipython3'.

**Comment by minad** [comment]
We will use the same profile. Ipython3 development will go into master

Am 15. März 2015 17:34:15 MEZ, schrieb "Leedy 刘当一" <notifications@github.com>:

**Comment by liudangyi** [comment]
The IPython protocol document is available [here](http://ipython.org/ipython-doc/dev/development/messaging.html).

**Comment by hattwj** [comment]
The kernel.json provided by sebroeder was exactly what I was looking for! 

I really like minad's idea about extending the cli interface with register/unregister options. 

liudangyi, couldn't the cli just pass a `--profile iruby` argument directly to ipython?

Also, since I am here specifically because I had trouble registering the ruby kernel, I would say that a register/unregister would be neat!

**Comment by minad** [comment]
@hattwj See https://github.com/SciRuby/iruby/commit/c93dddf23fcab44a9d90888a10f222734381146c

**Comment by agarie** [comment]
Hey folks! I'm using @sebroeder method to be able to create IRuby kernels with `ipython notebook` and Python 3.4, but auto-complete is currently broken.

I guess this is expected, as python3 still isn't fully supported. However, this is one of the only things that my coworkers really disliked about IRuby -- and they aren't even accustomed to IPython!

If there's any low-hanging fruit that I could work on my spare time, please tell me.

**Comment by minad** [comment]
@agarie iruby master already contains the patches to register ipython3 kernels. Please try that. The next thing to work on is the migration to the other 0mq library and the protocol update according to the new ipython specification.
