### ISSUE TITLE
Add more test cases and get travis-ci green

### ISSUE THREAD

**Issue by minad** [SciRuby/iruby#2]
Currently there are only a few tests. This is unacceptable if we want to achieve higher user adoption.
- Get travis-ci green
- Use https://github.com/jupyter/jupyter_kernel_test
- Increase coverage

**Comment by sebroeder** [comment]
Any preference on the testing framework?

**Comment by minad** [comment]
No, the one who works on this issue can choose. However I would prefer if we use something simple and widely adopted (minitest, rspec, etc.).

**Comment by sebroeder** [comment]
I started to work on this and did some research on testing frameworks suitable for command line tools. I am trying out https://github.com/cucumber/aruba at the moment.

Aruba can be used with RSpec instead of Cucumber, but it was easier for me to get started with Aruba and Cucumber because it was covered in detail in two books:
- Build Awesome Command-Line Applications in Ruby by David Copeland
- The Cucumber Book by Matt Wynne and Aslak Hellesøy

Unfortunately #5 (more specifically minad/iruby#47) is causing some problems for writing automated tests because without a working `quit` command in the IRuby console I cannot programmatically close the console front end (as far as I know).

From the 3 scenarios below, the Pry and IPython scenarios pass, but the IRuby scenario fails with 

```ruby
ChildProcess::TimeoutError: process still alive after 3 seconds
```

```gherkin
@announce
Feature: `iruby` Command Line Interface

  Scenario: Start and quit the Pry console
    When I run `pry` interactively
    And I type "puts 'Hello Pry'"
    And I type "quit"
    Then the stderr should not contain anything
    And the stdout should contain:
      """
      Hello Pry
      """

  Scenario: Start and quit the IPython console
    When I run `ipython console` interactively
    And I type "print('Hello IPython')"
    And I type "quit"
    Then the stderr should not contain anything
    And the stdout should contain:
      """
      Hello IPython
      """

  Scenario: Start and quit the IRuby console
    When I run `ipython console --kernel ruby` interactively
    And I type "puts Hello IRuby"
    And I type "quit"
    Then the stderr should not contain anything
    And the stdout should contain:
      """
      Hello IRuby
      """
```

I am trying to wrap my head around the kernel and backend code and why quit is not working, but have no idea yet. So any pointers in the right direction are very welcome :)

**Comment by minad** [comment]
Actually i dont want to have too complicated test frameworks like cucumber. Is it possible that you just use rspec or minitest?

Am 19. März 2015 13:23:34 MEZ, schrieb "Sebastian Röder" <notifications@github.com>:

**Comment by minad** [comment]
cucumber pulls five dependencies itself, this is just stupid and not a good idea for ci. It will also break in the future which is much less probable for something simple like just plain rspec/minitest. I really have to stress what I wrote above - It should be "something simple".

I hope this is ok for you.

**Comment by liudangyi** [comment]
I would suggest minitest, which is quite simple and small.

**Comment by minad** [comment]
@sebroeder Still interested in working on that?

**Comment by sebroeder** [comment]
@minad yes, still interested. I am just trying to get the priorities right, both between the different open issues in iruby and between iruby contributions and other projects in my life (university, upcoming internship, ...)

I understand and share your desire to keep testing *simple* but don't want to get into flame wars about testing frameworks. I have very little experience with minitest, some experience with RSpec and used Cucumber for the first time here. As I wrote earlier, my decision was based on the fact that I had good documentation/literature available for Cucumber + Aruba, so it was easier for me to get started, not that I am in general in favour of Cucumber. I also wrote that it would be possible to use Aruba with RSpec without Cucumber, but I would have to figure this out on my own, since there is not much documentation for that. So from my point of view it was/is still a good idea to **start** with Cucumber, possibly migrating to RSpec later (I also think tests in any framework ist better than no tests at all :wink:)    

So when we put the MiniTest/Rspec/Cucumber discussion aside, what do you think about Aruba? It solves for me the problems I had acceptance testing `command.rb` (so far), like making assertion on stdin/stdout, on presence/absence of files and file content.

I still could not find the problem and proper solution for `quit` not working and it seems not so easy to fix, because one has to understand in detail how the ipython console front end and iruby kernel/pry back end work together. It could go down to such low level stuff as the lifecycle of unix processes, signal handling etc. I there a good way to debug which messages are send over the message queue between front end and back end?  

So I might go back to working on the kernelspec stuff next, since this seems to be much easier to fix for an iruby-newbie, and come back here later.

If somebody comes up with easy to read and write tests for iruby in minitest or RSpec in the meantime, I am happy to read them and learn from others :smile:

**Comment by minad** [comment]
I understand your point about these frameworks to have information available. However minitest for example is much easier, since it is just plain ruby and not another language (cucumber) lying on top of it. I don't need a book or maybe no documentation at all to write simple assertions :)

About testing frameworks in ruby in general: Maybe this goes in the direction of a flame war. I think testing frameworks in ruby fall mostly in the category overengineering. They bring to many dependencies, break to easily, introduce additional unnecessary layers. There is a whole "testing framework industry" going on in ruby. There are libraries for mockups, fixture generation, testing dsl, acceptance tests ...  A lot of code someone has to maintain. And I am not sure if you want to dig into the libraries if something goes wrong.

For example a while ago I had the case if we should use https://github.com/jnicklas/capybara for https://github.com/slim-template/slim. However this library pulled dozens of dependencies and it was simply unnecessary. So we decided against it and everything works well the simple way.

However I admit there might be a reason to have these test frameworks. For example if you maintain a huge project with a team in a company and maybe you even have a team which exclusively writes tests. And this team will then be very much into the testing framework and will know exactly whats going on. Because I think if you use a framework, you have to know it at up to a certain level. Also what is going on internally. But you probably don't want to spend too much time to learn the internals since they are not needed for what we want to achieve here.

These testing frameworks are also a nightmare for package maintainers. Debian for example wants to execute tests for packages they include into the distribution. If they see that running the tests needs 10 additional packages, they won't be very happy. So I think it boils down to minitest or rspec.

nmatrix also uses rspec, take a look at the tests there if you want to see how to write those.

**Comment by liudangyi** [comment]
Maybe the integration test could be like this

```ruby
require "minitest/autorun"
require "open3"

class IntegrationTest < Minitest::Test
  def setup
    @stdin, @stdout, @stderr, @process = Open3.popen3("bin/iruby")
  end

  def teardown
    @stdin.close
    @stdout.close
    @stderr.close
    @process.kill
  end

  # We expect a process to print all its output at one time.
  # Otherwise this would break.
  def read
    @stdout.read_nonblock(4096)
  rescue IO::WaitReadable
    retry
  end

  def write(input)
    read # eat prompt
    @stdin.puts input
  end

  def test_hello_world
    write '"Hello, world!"'
    assert_match 'Hello, world!', read
    write 'puts "Hello, world!"'
    assert_match 'Hello, world!', read
    write '12 + 12'
    assert_match '24', read
  end

  def test_pry_functions
    write 'ls'
    assert_match "self.methods", read
  end
end
```

**Comment by minad** [comment]
@liudangyi Yes, something like that!
@sebroeder What do you think?

**Comment by minad** [comment]
@sebroeder Unfortunately, I don't have your email adress. Therefore I write you here. Do you want to take part at the GSOC? The deadline is Mar27 and you have to write an application in google melange until then. Are you interested in taking part? It would also be great if you could submit a pr until then.
