### ISSUE TITLE
Make this a proper fork.

### ISSUE THREAD

**Issue by rgbkrk** [SciRuby/iruby#23]
It would be good for folks to know that this is the "official" version by fully breaking it off from the originating repos, either by getting it transferred or by creating it as a wholly new repo. There might be a way to put a ticket in to GitHub to make this a source rather than a fork too. Not sure though.

**Comment by minad** [comment]
I don't know how this is done. I don't think github offers such a possibility. My repository clearly states that development has shifted here. Also the new gem refers to this repository.

**Comment by minad** [comment]
However I could clone the whole thing, but I don't think thats such a good idea. I improved the description on my old repo a bit.

But usually the source specified by the gem from rubygems.org is considered the canonical source.

**Comment by agarie** [comment]
As a matter of fact, GitHub support can convert a fork to a non-forked repository. I did this myself, once, with this gem: [Measurable](https://github.com/agarie/measurable). It was originally a fork of [Distance Measures](https://github.com/reddavis/Distance-Measures).

I simply sent a support ticket asking for it to be converted to a true repository because of the original's inactiveness and the different purposes of the gems. As you are the creator of the original repo, there shouldn't be any problem. :)
