### ISSUE TITLE
Support `%%javascript` directive

### ISSUE THREAD

**Issue by neumanrq** [SciRuby/iruby#258]
Jupyter supports executing JavaScript code inline by the directive `%%javascript`, i.e. a a cell with

```
%%javascript
// JS code goes here
alert("Hey");
```
should execute the JS code and produce the alert message box. 

However, maybe I have overseen something - but I think unfortunately this does not work together with `iruby` yet:
![Bildschirmfoto 2019-10-25 um 16 39 24](https://user-images.githubusercontent.com/3685123/67580404-9456d200-f746-11e9-9a8c-2bab98c5b382.png)

Here's how it should look like, as it does work with python3 kernel:
![Bildschirmfoto 2019-10-25 um 16 40 27](https://user-images.githubusercontent.com/3685123/67580420-9f116700-f746-11e9-82b9-dbcb37636dec.png)

**Comment by kojix2** [comment]
Hello, Mr. neumanrq.

Hi @neumanrq

Thank you for your request.

IRuby dose not support magic commands. Magic commands have been discussed several times in the past. But for now, we're not going to support magic commands into IRuby.  

The reason is that there are not many people to maintain IRuby and my skills are low. Other Jupyter kernels, such as IJulia, do not support magic commands too.

Another reason why we don't want to support magic commands is that in Ruby, sometimes line start with "%".

```ruby
%w[apple banana orange strawberry]
%i[cat dog]
```

But, you can run simple Javascript like this. 

```ruby
IRuby.display('alert("Hey");', mime: "text/javascript")
```
![image](https://user-images.githubusercontent.com/5798442/67629576-f3d5ee80-f8ba-11e9-9b84-af5b2631f73c.png)

**Comment by neumanrq** [comment]
Hi @kojix2,

thanks for your feedback and sharing your thoughts on that topic. The decision makes totally sense to me - I just did not know about the scope IRuby covers in this direction. The arguments against supporting the magic directives are really reasonable. 

Also, thanks for your work on the project - I really appreciate this!
