### ISSUE TITLE
Kernel dies occasionally

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#31]
It works at times, but sometimes the kernel suddenly dies with this backtrace:

```

[2015-06-03T00:28:50.445538 #7036] FATAL -- : Kernel died: cannot load such file -- iruby
/home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/lib/iruby/command.rb:73:in `require'
/home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/lib/iruby/command.rb:73:in `run_kernel'
/home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/lib/iruby/command.rb:33:in `run'
/home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/bin/iruby:5:in `<top (required)>'
/home/sameer/.rvm/gems/ruby-2.2.1/bin/iruby:23:in `load'
/home/sameer/.rvm/gems/ruby-2.2.1/bin/iruby:23:in `<main>'
/home/sameer/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/sameer/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
/home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/lib/iruby/command.rb:73:in `require': cannot load such file -- iruby (LoadError)
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/lib/iruby/command.rb:73:in `run_kernel'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/lib/iruby/command.rb:33:in `run'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/iruby-0.2.4/bin/iruby:5:in `<top (required)>'
	from /home/sameer/.rvm/gems/ruby-2.2.1/bin/iruby:23:in `load'
	from /home/sameer/.rvm/gems/ruby-2.2.1/bin/iruby:23:in `<main>'
	from /home/sameer/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/sameer/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by v0dro** [comment]
To provide more details, this happens only if I run `iruby notebook` in a directory apart from where my iruby has been cloned. (`/home/sameer/gitrepos/iruby/` in my case).

**Comment by v0dro** [comment]
Any ideas on this? I'm unable to run iruby notebook anywhere but in the directory of cloned iruby code.

**Comment by minad** [comment]
Some problem with the $LOAD_PATH

It seems you are running from the gem and not the cloned iruby repository. Also bundler could be an issue since the kernel tries to load the current Gemfile by requiring bundler/setup

**Comment by minad** [comment]
ruby load path management, gems, bundler - this is really a mess

**Comment by minad** [comment]
Remember to always do a iruby register --force if you change the location of the iruby command.

I tested the following cases:

* WORKS - Running cloned iruby from a cloned iruby directory
* WORKS - Running cloned iruby from a different repository
* WORKS - Running iruby gem from a directory without a gemfile
* WORKS - Running iruby gem from a directory with a gemfile requiring iruby
* FAILS - Running iruby gem from a directory with a gemfile NOT requiring iruby

I cannot reproduce your problem.

**Comment by v0dro** [comment]
My problem is covered in the last two cases that you report as failed.

Also try to `require 'statsample'`, or any gem that is not listed in the gem file. it should fail.

Currently to make a few notebooks I'm adopting a hack where I run `./iruby notebook` from `iruby/bin` after having added the following to my Gemfile:

```
gem 'statsample'
gem 'daru'
```

**Comment by minad** [comment]
The two last failures are known "issues", but they are by design. If you want to use iruby from a project with a Gemfile, you have to require iruby in it.

I recommend the following Gemfile:

~~~ ruby
source 'https://rubygems.org/'

# Your project gems
gem 'statsample'
gem 'daru'
...

# Gems only needed if we want to use iruby
group :iruby do
  gem 'iruby'
  gem 'pry'
  ...
end

**Comment by v0dro** [comment]
But why should it be this way?

If the browser based notebook is meant to be  a more enhanced and interactive version of the pry or irb shells, should I not be able to do the same things that I do in the shell; in iruby?

So for instance we don't need to bother about the directory location when running `pry` or `irb`. Why not keep it like that here?

And if you're planning to keep this design I think it should be well documented. I spent quite a while trying to figure this out.

**Comment by minad** [comment]
Well, this is by design of bundler. If we use it, this is what we get. iruby just loads a Gemfile if available by `require 'bundler/setup'`.

I see it this way - there are three cases:

1. You don't use bundler - then there is no Gemfile. This is done for example in those docker images, all gems are just installed as root. There won't be any problems.
2. You use bundler in your project. There is a Gemfile, it should be loaded. The Gemfile should mention iruby since you want to use it.
3. You want to use bundler PARTIALLY, there is a Gemfile which you probably expect to be loaded. But the Gemfile doesn't mention iruby. So this fails.

I think the 3. case is what you are currently in and complaining about. I don't know if there is a way around it.

I also wasn't happy with bundler in the beginning, because I also wanted to use gems that were not part of the Gemfile. This is not allowed by the design of bundler, because bundler ensures that no wrong gems and versions are loaded. Therefore use it right and mention ALL gems that are used including iruby.

Those things also apply to pry. For irb not so much since it is always there as part of the stdlib.

**Comment by v0dro** [comment]
Would you consider using hen instead of bundler?

[rb-gsl](https://github.com/blackwinter/rb-gsl) currently uses it.

**Comment by minad** [comment]
Hen is a helper providing rake tasks and not really a replacement for bundler.

Am 4. Juni 2015 07:55:47 MESZ, schrieb Sameer Deshmukh <notifications@github.com>:

**Comment by AbhimanyuAryan** [comment]
@minad @v0dro can you help me with my error: http://stackoverflow.com/questions/35999925/kernel-dies-when-creating-iruby-notebook/ ?
