### ISSUE TITLE
Shutdown takes 5 seconds per kernel

### ISSUE THREAD

**Issue by ankane** [SciRuby/iruby#311]
Hi, it looks the kernel shutdown is timing out every time.

```text
Shutdown this notebook server (y/[n])? y
[C 11:06:28.858 NotebookApp] Shutdown confirmed
[I 11:06:28.860 NotebookApp] Shutting down 3 kernels
[I 11:06:28.861 NotebookApp] Kernel shutdown: ac819a12-7ff7-4d8d-b414-91c888076d63
[I 11:06:33.972 NotebookApp] Kernel shutdown: 810fb64e-b04c-487f-b28c-abfb2490e588
[I 11:06:39.082 NotebookApp] Kernel shutdown: 61112573-bc7a-463f-8ee2-d4e66d6b4106
[I 11:06:44.195 NotebookApp] Shutting down 0 terminals
```

From what I can tell, it's due to [this line](https://github.com/SciRuby/iruby/blob/58dc86a170a988db9367e29879f6877012862fd6/lib/iruby/kernel.rb#L133) blocking indefinitely.

**Comment by mrkn** [comment]
I guess we need to introduce the control channel and support [`shutdown_request` message](https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-shutdown) to fix this issue.

I'm working on introducing the control channel due to debugger support.  I'll extract the control channel part and add `shutdown_request` support in the new branch asap.  Stay tuned.

**Comment by ankane** [comment]
Cleaning up issues
