### ISSUE TITLE
encoding issue?

### ISSUE THREAD

**Issue by kozo2** [SciRuby/iruby#61]
The cell[8] works fine on the command line, but on iruby notebook fails like this.
https://gist.github.com/kozo2/cfc5b7606cbfa7e8b5f4

Please refer to the following issue
https://github.com/SciRuby/sciruby-notebooks/pull/6

**Comment by MatthiasWinkelmann** [comment]
Ran into this problem with a notebook that include some hashing:

```
> Digest::SHA256.digest('hello world').to_json
Encoding::UndefinedConversionError: "\xB9" from ASCII-8BIT to UTF-8
```

`digest` returns a string with ASCII-8BIT encoding, which the json-encoder is trying to convert to UTF-8, which fails. You're not seeing it on the command line because the json-encoding  step only happens for jupyter.  

I don't have the time to track it down, but it appears[ this 4-year old bug](https://bugs.ruby-lang.org/issues/6799) is related and it may be a problem with String.unpack. 

You can try adding `# encoding: utf-8` as the first line in your notebook, or possibly call force_encoding('UTF-8') on misbehaving strings.

**Comment by kojix2** [comment]
@kozo2 
The cell[8] works on my Ubuntu computer in 2019. 
https://gist.github.com/kojix2/d034e6689f356db773ae6ab963666c91

Do you still get errors?
And which operating system did you use?

**Comment by kojix2** [comment]
I close this issue due to inactivity. 
Please feel free to reopen the issue and let us know if its cause still persists with the current version of IRuby. Thank you.
